### ISSUE TITLE
Refactor integration tests

### ISSUE THREAD

**Issue by Rubilmax** [morpho-org/morpho-blue#488]
From: https://github.com/morpho-labs/morpho-blue/pull/429

1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325820921
2. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1310275241
1. [ ] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325818924
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325823705
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325846767
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325909674
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325911424
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325911858
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325921066
1. [ ] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325924939
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325646947
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325649180
1. [ ] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325654442
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325655471
1. [x] https://github.com/morpho-labs/morpho-blue/pull/429#discussion_r1325677876

**Comment by MathisGD** [comment]
missing invariants are now covered by formal verification
