### ISSUE TITLE
The liquidations formula might be too restrictive

### ISSUE THREAD

**Issue by alcueca** [morpho-org/morpho-blue#536]
While acknowledging that there are several approaches to liquidations in the whitepaper, Morpho Blue chooses a specific formula for liquidations:

<img width="740" alt="image" src="https://github.com/morpho-org/morpho-blue/assets/38806121/31ab1ea5-9de5-4a4a-9751-3f71b8d141e9">

The same as the interest rate is an external whitelisted module, so can be the liquidation formulas be delegated to whitelisted modules, as different formulas might work better for different assets depending on volatility or volume.

**Comment by QGarchery** [comment]
It's an interesting topic to discuss, happy to have your point of view on this !

You are right that the formula to determine the liquidation incentive factor (LIF) is fixed. This is a trade-off that has been considered taking into account the following arguments:
1. this formula is already designed to be tailored to different assets. The general approach has not yet been made public, but the idea is that different pair of assets will typically use different sets of LLTVs. By looking at how those pairs would plot in a LIF / LLTV graph, we can interpolate to find a best estimate of this formula. Note that this formula is consistent in the end with the data from Aave and Compound !
2. increasing the granularity of the liquidation incentive comes with an increased liquidity fragmentation risk. One could create a similar market but with a different liquidation incentive factor. There are mitigation to this risk, but it's best if it's kept to a minimum to begin with.
3. this formula allows to bundle 2 risk parameters into one: from the LLTV you can deduce the LIF. Having one parameter eases the understanding of the market, enforces a standard, and makes it easier to foster competition on it. As an example, if two markets differ only in LLTV, it would make sense that lenders would prefer lending in the lower LLTV one.
4. risk parameters are harder to foster competition on than rates. It's harder to understand their impact and they are more subjective, whereas an increased rate is simply better for lenders and worse for borrowers. This is a reason why it makes less sense to increase granularity on the risk parameters
