### ISSUE TITLE
The Cantina security review has a "draft" overlay

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/morpho-blue#597]

**Comment by QGarchery** [comment]
Let's ask for the watermark on [audits/2023-11-13-cantina-managed-review-draft.pdf](https://github.com/morpho-org/morpho-blue/blob/f463e40f776acd0f26d0d380b51cfd02949c8c23/audits/2023-11-13-cantina-managed-review-draft.pdf) to be removed
