### ISSUE TITLE
Should `expectedAssets` precise the rounding

### ISSUE THREAD

**Issue by MathisGD** [morpho-org/morpho-blue#660]
these functions round in a certain way (the "natural way"), but don't say in their name what they are doing. It probably caused an issue in mm. Should we rename them ?

https://github.com/morpho-org/morpho-blue/blob/55d2d99304fb3fb930c688462ae2ccabb1d533ad/src/libraries/periphery/MorphoBalancesLib.sol#L90-L120

**Comment by Rubilmax** [comment]
What shall we do?

**Comment by QGarchery** [comment]
I don't think it's worth changing now
