### ISSUE TITLE
are you deploy to Sepolia Testnet yet?

### ISSUE THREAD

**Issue by psychonaute** [morpho-org/morpho-blue#667]

**Comment by tomrpl** [comment]
Hey @psychonaute 

There has been a rough deployment done here, not maintain at all, if you need:

 cf: :warning: Sepolia :warning:
1. Morpho Blue contract here: 0xD087aE28Dc73D0C91D2f060737093D833bdF3EE4
(can't manage to verify it though, and the one who deployed is OOO until monday)
2. AdaptiveCurveIRM contract here: 0xbbefD3Af6EF8766cD4C3755Cf10bf87F877a49d7 and verified
3. usdc_weth_oracle deployed here: 0x7Fb1Cc991160e6212f83eF86e92A4A61efCa4321 for the market with ->
LoanToken:
USDC 0xf08a50178dfcde18524640ea6618a1f965821715
CollateralToken:
WETH 0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
4. Market created USDC (WETH, AdaptiveCurveIRM, usdc_weth_oracle, 90%)
id:
0x923d1403cd39dd8297b19f1644ffd635ac2b987ea6b636ca6130079d7425a07b
address loanToken -> 0xf08a50178dfcde18524640ea6618a1f965821715 USDC
address collateralToken -> 0x7b79995e5f793A07Bc00c21412e50Ecae098E7f9
address oracle -> 0x7Fb1Cc991160e6212f83eF86e92A4A61efCa4321
address irm -> 0xbbefD3Af6EF8766cD4C3755Cf10bf87F877a49d7
uint256 lltv-> 915000000000000000
